### ISSUE TITLE
Crash on Lollipop

### ISSUE THREAD

**Issue by pejakm** [n76/Local-GSM-Backend#25]
ROM: [BlissPop unofficial for LG p880](http://forum.xda-developers.com/optimus-4x-hd/development/rom-blisspop-p880-t3042583)

App version: [v0.9.0 from F-Droid](https://f-droid.org/repository/browse/?fdfilter=Local&fdid=org.fitchfamily.android.gsmlocation)

```
E/AndroidRuntime( 7451): FATAL EXCEPTION: main
E/AndroidRuntime( 7451): Process: org.fitchfamily.android.gsmlocation, PID: 7451
E/AndroidRuntime( 7451): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fitchfamily.android.gsmlocation/org.fitchfamily.android.gsmlocation.settings}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
E/AndroidRuntime( 7451): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
E/AndroidRuntime( 7451): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2421)
E/AndroidRuntime( 7451): 	at android.app.ActivityThread.access$900(ActivityThread.java:153)
E/AndroidRuntime( 7451): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
E/AndroidRuntime( 7451): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7451): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 7451): 	at android.app.ActivityThread.main(ActivityThread.java:5354)
E/AndroidRuntime( 7451): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7451): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7451): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
E/AndroidRuntime( 7451): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 7451): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
E/AndroidRuntime( 7451): 	at org.fitchfamily.android.gsmlocation.prefsFragment.onCreate(prefsFragment.java:39)
E/AndroidRuntime( 7451): 	at android.app.Fragment.performCreate(Fragment.java:2031)
E/AndroidRuntime( 7451): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
E/AndroidRuntime( 7451): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
E/AndroidRuntime( 7451): 	at android.app.BackStackRecord.run(BackStackRecord.java:834)
E/AndroidRuntime( 7451): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
E/AndroidRuntime( 7451): 	at android.app.Activity.performStart(Activity.java:6005)
E/AndroidRuntime( 7451): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2322)
E/AndroidRuntime( 7451): 	... 10 more
```

**Comment by n76** [comment]
Already discovered and fixed in 0.9.1 which apparently is not yet on F-Droid

**Comment by pejakm** [comment]
Great, thanks!

**Comment by pejakm** [comment]
Reported to F-Droid, they pointed out that this new version isn't released yet (their system watches [releases](https://github.com/n76/Local-GSM-Backend/releases) page). If this new version isn't released yet intentionally then I apologize for bringing this up. :)

**Comment by n76** [comment]
You are correct, I had neglected to push the tagging to github.

**Comment by agilob** [comment]
Thanks, it's my bad.

**Comment by pejakm** [comment]
Thanks guys!
