### ISSUE TITLE
MLS generate database: 404

### ISSUE THREAD

**Issue by helllamer** [n76/Local-GSM-Backend#28]
*Steps to reproduce*:
1. Cyanogen 12.1 (android 5.1)
2. Install local gsm backend from f-droid (0.9.2)
3. Go to backend settings
4. Enable MLS checkbox
5. Push "generate database" button

*Result*:
Nothing downloaded.
No errors on the device screen (only some useless log messages).
adb logcat shows:
```
I/Timeline( 5055): Timeline: Activity_idle id: android.os.BinderProxy@32df6d82 time:1755732
W/System.err( 5055): java.io.FileNotFoundException: https://d17pt8qph6ncyq.cloudfront.net/export/MLS-full-cell-export-2015-08-04T000000.csv.gz
W/System.err( 5055): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
W/System.err( 5055): 	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
W/System.err( 5055): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
W/System.err( 5055): 	at org.fitchfamily.android.gsmlocation.dlFragment$downloadDataAsync.getData(dlFragment.java:461)
W/System.err( 5055): 	at org.fitchfamily.android.gsmlocation.dlFragment$downloadDataAsync.doInBackground(dlFragment.java:359)
W/System.err( 5055): 	at org.fitchfamily.android.gsmlocation.dlFragment$downloadDataAsync.doInBackground(dlFragment.java:194)
W/System.err( 5055): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/System.err( 5055): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err( 5055): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err( 5055): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 5055): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 5055): 	at java.lang.Thread.run(Thread.java:818)
```

*Expected result*:
DB should be downloaded OR error/hint shown on the screen.

UPD#1: URL became available again after ~1 hour.

**Comment by helllamer** [comment]
Sorry, looks like download error was shown on the screen, I've missed it.
